server:
  port: 15555

logging:
  group:
    boot: org.springframework.boot,org.springframework.boot.autoconfigure,org.springframework.boot.logging,org.springframework.boot.context,org.springframework.boot.web,org.springframework.boot.admin
  level:
    root: info
    web: info
    sql: debug
    tomcat: info
    boot: info
    org:
      springframework:
        jdbc:
          core: debug
        apache:
          ibatis:
            logging: debug
    com:
      cacoota: trace

spring:
  thymeleaf:
    enabled: true
    cache: false
    suffix: .html
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: ENC(Mu3hZTFCKx5/DN4wgVa7i6t0LBCNkKX9PWM5M4epYSZzbUKljyyOssePFWoLS7iWfuM0afYWktsFp6pJikdqR59lhEK+vZ+zVeYd+xnY9xNwXsgw7qahs3HPTQMRQGeFkN8M2nG76RT7gF/5hvyjpvKCdSJnxbmNWVWL+kP+sdFzxkbAWdbYfd9vG87eeDtsPG0aGetne3A+zJ3Pw/+eSUax7dEgpUdf4IBVH5hN1u4=)
      username: ENC(Ysj+Zkk6WLIx6dpD+gAs0iij440SWqc/NIXOCsMf2ky4rLaL23Gp/wnnG4WqBbsA)
      password: ENC(q4vCQmkuZd9Ckc05Gyw38440q1hrt+iT2EP2G5T9xf7EK9ypNLn/fwPRSAgxn3eL)
      initial-size: 5
      min-idle: 3
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
#  redis:
#    cluster:
#      nodes: ENC(Xq8qI7MDH7uMegBZ077fQG/u9SUE8jiTQ5Y0k8MpmZXj67qF2HoNKCYGq4hPYTLG/tfws+R7Hs8Pbg2obYDiGgXszVuu1bVasJF7IBOzAAQ=)
#    password:
#    timeout: 30000
#    lettuce:
#      pool:
#        max-active: 200
#        max-idle: 20
#        min-idle: 5
#        max-wait: 5000
  data:
    mongodb:
      host: ENC(IJx+2rlwM+NvB302Yuhv27XcelSQjspCaU/7H/MicszIVsD8IZIw1xUxf0yei6qD)
      port: 15011
      database: ENC(Dnn6DPsM06y+NmcjzJi4VaFJl0v20FhM5ao69/YjhIjDoDV6NdwBsbPchlGT9tWf)
      username: ENC(WYoJjJY3ypRqqtI/UHwXS2rrjatLxALIHL2xX/bO8H71liW1/lWoj19bf60Tzv9C)
      password: ENC(akudvc3iCzlHwj75GFaHH8PbGVGuplmdfn8NXaCyo432bIt+9KtgwX5wJsj+2xtd)
    elasticsearch:
      cluster-name: ENC(Gg0KhclsNVojwEkDVMp2OEwDYElicdw6do8KnkEnmdhOwny1aNWEYX90qtQi0TT2)
      cluster-nodes: ENC(vxV3RDMgzUbvbh2Yr0mtel+Sn6wVTeLIwezAN916t/MpIyyeHWwhZjlDsyJpKH3HOuTKt0q9Sb0edC6/UL4eXhwBaWev/HBzhXjgKxnFKFI=)
      properties:
        transport:
          tcp:
            connect_timeout: 120s

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.cacoota.*.mybatis.model

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

study:
  task:
    hack:
      init: 60000
      fixed: 30000